config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :weigh_ins#, only: [:create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :weigh_ins, dependent: :destroy
  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def feed
    WeighIn.where("user_id = ?", id)
    #Micropost.where("user_id = ?", id)
  end
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  private
    
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/models/weigh_in.rb
class WeighIn < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('day DESC')}
  validates :day, presence: true
  validates :weight, presence: true
  validates :user_id, presence: true
  
  def self.weight_on(date, user_id)
    where("date(day) = ? and user_id = ?", date, user_id).sum(:weight)
  end
  
  def self.percent_body_fat_on(date, user_id)
    where("date(day) = ? and user_id = ?", date, user_id).sum(:percent_body_fat)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end
  
  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      #@micropost = current_user.microposts.build
      @weigh_in = current_user.weigh_ins.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @current_user_id = current_user.id
      sDate = params[:start_date]
      if sDate.nil?
        @start_date = 3.weeks.ago.to_date
      else
        @start_date = sDate
      end
      
      eDate = params[:end_date]
      if eDate.nil?
        @end_date = Date.today
      else
        @end_date = eDate
      end
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    @weigh_ins = @user.weigh_ins.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/weigh_ins_controller.rb
class WeighInsController < ApplicationController
  def index
  end
  
  def create
    @weigh_in = current_user.weigh_ins.build(weigh_in_params)
    w = WeighIn.find_by(user_id: @weigh_in.user_id, day: @weigh_in.day)
    if not w.nil?
      w.weight = @weigh_in.weight
      w.percent_body_fat = @weigh_in.percent_body_fat
      w.save
      flash[:success] = "WeighIn updated!"
      redirect_to root_url
    elsif @weigh_in.save
      flash[:success] = "WeighIn created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
  
  private

    def weigh_in_params
      params.require(:weigh_in).permit(:day, :weight, :percent_body_fat, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:rememeber_token)
    self.current_user = nil
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Agustin (Gus) Muniz
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
	      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	        <div class="container">
	          <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	              <span class="sr-only">Toggle navigation</span>
	              <span class="icon-bar"></span>
	              <span class="icon-bar"></span>
	              <span class="icon-bar"></span>
	            </button>
	            <%= link_to "weight tracker", root_path, id: "logo" %>
	          </div>
	          <div class="navbar-collapse collapse">
	            <ul class="nav navbar-nav">
	              <li class="active"><%= link_to "Home", root_path %></li>
	              <li><%= link_to "Help", help_path %></li>
				  <% if signed_in? %>
				    <li><%= link_to "Users", users_path %></li>
				    <li id="fat-menu" class="dropdown">
				      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				        Account <b class="caret"></b>
				      </a>
				      <ul class="dropdown-menu">
				        <li><%= link_to "Profile", current_user %></li>
				        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
				        <li class="divider"></li>
				        <li>
				          <%= link_to "Sign out", signout_path, method: "delete" %>
				        </li>
				      </ul>
				    </li>
				  <% else %>
				    <li><%= link_to "Sign in", signin_path %></li>
				  <% end %>
	            </ul>
	          </div><!--/.nav-collapse -->
	        </div>
	      </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", "jquery-ui", media: "all",
                                           "data-turbolinks-track" => true %>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "jquery-1.11.1.min", "jquery-ui.min", "rails", "highcharts" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	  <% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %>"><%= value %></div>
	  <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content">Day: <%= feed_item.day %>, Weight: <%= feed_item.weight %></span>
  <% if not feed_item.percent_body_fat.nil? %>
    <span class="content">% body fat: <%= feed_item.percent_body_fat %></span>
  <% end %>
  <% if not feed_item.note.nil? and feed_item.note.length > 0 %>
    <span class="content">Note: <%= feed_item.note %></span>
  <% end %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.weigh_ins.count, "weigh in") %>
</span>

app/views/shared/_weigh_in_form.html.erb
<p>Enter your weigh in for the day</p>
<%= form_for(@weigh_in) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
	<%= f.label :day %>
	<%= f.text_field :day, :value => Date.today  %>
	<%= f.label :weight %>
    <%= f.text_field :weight, placeholder: "enter weight...(required)" %>
	<%= f.label :percent_body_fat %>
	<%= f.text_field :percent_body_fat, placeholder: "enter % body fat...(optional)" %>
	<%= f.label :note %>
	<%= f.text_area :note, placeholder: "enter note...(optional)" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<script type="text/javascript" charset="utf-8">
function reloadChart() {
    new Highcharts.Chart({
  	  chart: {
  		  renderTo: "weight_chart"
  	  },
  	  title: {
  		  text: "Weight by Day"
  	  },
  	  xAxis: {
  		  type: "datetime"
  	  },
  	  yAxis: {
  		  title: {
  			  text: "Weight"
  		  }
  	  },
  	  tooltip: {
  		  formatter: function() {
  			  return Highcharts.dateFormat("%B %e, %Y", this.x) + ": " + Highcharts.numberFormat(this.y, 1);
  		  }
  	  },
  	  series: [{
  		  name: "Weight",
  		  pointInterval: <%= 1.day * 1000 %>,
  		  pointStart: <%= @start_date.to_time.to_i * 1000 %>,
  		  data: <%= (@start_date..@end_date).map { |date| WeighIn.weight_on(date, @current_user_id).to_f }.inspect %>
  	  }, {
  		  name: "% Body Fat",
  		  pointInterval: <%= 1.day * 1000 %>,
  		  pointStart: <%= @start_date.to_time.to_i * 1000 %>,
  		  data: <%= (@start_date..@end_date).map { |date| WeighIn.percent_body_fat_on(date, @current_user_id).to_f }.inspect %>
  	  }]
    });	
}
	
function homeReload() {
  window.document.location.href = '/?start_date=' + document.getElementById("start_date").value + '&end_date=' + document.getElementById("end_date").value;
}
$(function() {	
  reloadChart();
});
</script>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
	  
	  <input id="start_date" name="start_date" type="text" value=<%= @start_date %>>
	  <input id="end_date" name="end_date" type="text" value=<%= @end_date %>>
	  <button type="button" onclick="homeReload()">Reload Chart</button>
	  <div id="weight_chart" style="width:560px; height:300px;"></div>
	  
      <section>
        <%= render 'shared/weigh_in_form' %>
      </section>
    </aside>
	<div class="span8">
	  <h3>Micropost Feed</h3>
	  <%= render 'shared/feed' %>
	</div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Weight Tracker</h1>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
      <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
      <% end %>
    </div>
</div>

app/views/weigh_ins/index.html.erb
hi